-- 001_create_rarities.sql
-- テーブル: rarities

CREATE TABLE IF NOT EXISTS public.rarities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  label TEXT,
  color TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- インデックス: code は UNIQUE により自動的にインデックス化
-- 使い方: 管理画面から code (例: N, R, SR, UR) と任意のラベル/カラーを追加してください
