-- 002_create_attributes.sql
-- テーブル: attributes

CREATE TABLE IF NOT EXISTS public.attributes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 属性 (例: fire, water, electric, cute など) をここに追加します。
