-- 003_create_pet_master_attributes.sql
-- 中間テーブル: pet_master_attributes (pet_masters と attributes の多対多)

CREATE TABLE IF NOT EXISTS public.pet_master_attributes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_master_id BIGINT NOT NULL REFERENCES public.pet_masters(id) ON DELETE CASCADE,
  attribute_id BIGINT NOT NULL REFERENCES public.attributes(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(pet_master_id, attribute_id)
);

-- 使い方: ペット登録時にこのテーブルへ (pet_master_id, attribute_id) の組を追加します。
