-- 005_create_games.sql
-- テーブル: games（ゲームマスタ）

CREATE TABLE IF NOT EXISTS public.games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  game_type TEXT NOT NULL, -- 'clicker', 'puzzle', 'rhythm', 'memory' など
  difficulty INTEGER DEFAULT 1, -- 難易度（1-5）
  unlocked_by_clear_count INTEGER DEFAULT 0, -- このゲームをアンロックするために必要なクリア数
  points_on_clear INTEGER DEFAULT 100, -- クリア時のポイント
  thumbnail_url TEXT,
  display_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_games_active_order ON public.games (is_active, display_order);
