-- 006_create_game_progress.sql
-- テーブル: game_progress（ユーザーのゲーム進捗）

CREATE TABLE IF NOT EXISTS public.game_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  game_id BIGINT NOT NULL REFERENCES public.games(id) ON DELETE CASCADE,
  clear_count INTEGER DEFAULT 0,
  best_score INTEGER DEFAULT 0,
  last_played_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, game_id)
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_game_progress_user ON public.game_progress (user_id);
CREATE INDEX IF NOT EXISTS idx_game_progress_game ON public.game_progress (game_id);
CREATE INDEX IF NOT EXISTS idx_game_progress_user_game ON public.game_progress (user_id, game_id);
