-- 007_create_user_game_unlocks.sql
-- テーブル: user_game_unlocks（ユーザーのゲームアンロック状況）

CREATE TABLE IF NOT EXISTS public.user_game_unlocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  game_id BIGINT NOT NULL REFERENCES public.games(id) ON DELETE CASCADE,
  unlocked_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, game_id)
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_user_game_unlocks_user ON public.user_game_unlocks (user_id);
CREATE INDEX IF NOT EXISTS idx_user_game_unlocks_game ON public.user_game_unlocks (game_id);
