-- 009_create_game_rewards.sql
-- ゲームクリア時の報酬/クーポンテーブル

CREATE TABLE IF NOT EXISTS public.game_rewards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  game_id BIGINT NOT NULL REFERENCES public.games(id) ON DELETE CASCADE,
  spot_id BIGINT REFERENCES public.spots(id) ON DELETE SET NULL,
  reward_code TEXT NOT NULL UNIQUE, -- QRコード用ユニークコード
  reward_type TEXT NOT NULL, -- 'coupon', 'item', 'points' など
  reward_value TEXT, -- クーポンコード、アイテムID、ポイント数など
  description TEXT, -- 報酬説明
  qr_data TEXT, -- QRコード化するデータ
  is_used BOOLEAN DEFAULT false,
  used_at TIMESTAMP WITH TIME ZONE,
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- インデックス
CREATE INDEX IF NOT EXISTS idx_game_rewards_user ON public.game_rewards (user_id);
CREATE INDEX IF NOT EXISTS idx_game_rewards_user_game ON public.game_rewards (user_id, game_id);
CREATE INDEX IF NOT EXISTS idx_game_rewards_code ON public.game_rewards (reward_code);
CREATE INDEX IF NOT EXISTS idx_game_rewards_is_used ON public.game_rewards (is_used);
